### ISSUE TITLE
Sealing key not tethered to measurement

### ISSUE THREAD

**Issue by khushboo-dfn** [AMDESE/sev-guest#1]
If we have same software (VM) running on multiple hosts, is it possible for us to have sealing key depend on Guest provided data and not on the measurement?
As per the [spec](https://www.amd.com/system/files/TechDocs/56860.pdf) (section 7.2), it appears that a sealing key can be derived just with the data provided by the Guest (in tandem with use of Migration Agent) and all the host specific fields are optional.

**Comment by jlarrew** [comment]
If I understand correctly, you just want to have a secret derived that is the same across hosts but can be personalized by the guest itself. Is that right?

You are correct that the measurement is optional, so the guests can opt to not mix that in. Since the guest itself possesses the final secret output by the guest message, it's free to use the secret as input to another KDF along with any other data it wants.

**Comment by jlarrew** [comment]
Hi @khushboo-dfn,

Since the original question is answered, I'm closing this issue. If you have any follow-up questions, feel free to re-open. Thanks!

Sincerely,
Jesse
